use crate::registry::{HookDefinition, HookSemantics, HookSource, StatePosition};

pub const BUILTIN_THIRD_PARTY_HOOKS: &[HookDefinition] = &[
    // React Query / TanStack Query
    HookDefinition {
        name: "useQuery",
        semantics: HookSemantics::State,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::ThirdParty,
    },
    HookDefinition {
        name: "useMutation",
        semantics: HookSemantics::State,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::ThirdParty,
    },
    HookDefinition {
        name: "useInfiniteQuery",
        semantics: HookSemantics::State,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::ThirdParty,
    },
    HookDefinition {
        name: "useSuspenseQuery",
        semantics: HookSemantics::State,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::ThirdParty,
    },
    // SWR
    HookDefinition {
        name: "useSWR",
        semantics: HookSemantics::State,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::ThirdParty,
    },
    HookDefinition {
        name: "useSWRInfinite",
        semantics: HookSemantics::State,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::ThirdParty,
    },
    // Zustand
    HookDefinition {
        name: "useStore",
        semantics: HookSemantics::State,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::ThirdParty,
    },
    // Redux
    HookDefinition {
        name: "useSelector",
        semantics: HookSemantics::State,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::ThirdParty,
    },
    HookDefinition {
        name: "useDispatch",
        semantics: HookSemantics::Unknown,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: false,
        source: HookSource::ThirdParty,
    },
    // Jotai
    HookDefinition {
        name: "useAtom",
        semantics: HookSemantics::State,
        state_position: Some(StatePosition {
            value: 0,
            setter: 1,
        }),
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::ThirdParty,
    },
    HookDefinition {
        name: "useAtomValue",
        semantics: HookSemantics::State,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::ThirdParty,
    },
    HookDefinition {
        name: "useSetAtom",
        semantics: HookSemantics::Unknown,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: false,
        source: HookSource::ThirdParty,
    },
    // React Router
    HookDefinition {
        name: "useNavigate",
        semantics: HookSemantics::Unknown,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: false,
        source: HookSource::ThirdParty,
    },
    HookDefinition {
        name: "useParams",
        semantics: HookSemantics::State,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: false,
        source: HookSource::ThirdParty,
    },
    HookDefinition {
        name: "useLocation",
        semantics: HookSemantics::State,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::ThirdParty,
    },
    // React Hook Form
    HookDefinition {
        name: "useForm",
        semantics: HookSemantics::Custom,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: false,
        source: HookSource::ThirdParty,
    },
    HookDefinition {
        name: "useController",
        semantics: HookSemantics::State,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::ThirdParty,
    },
];
