use crate::registry::{HookDefinition, HookSemantics, HookSource, StatePosition};

pub const BUILTIN_HOOKS: &[HookDefinition] = &[
    HookDefinition {
        name: "useState",
        semantics: HookSemantics::State,
        state_position: Some(StatePosition { value: 0, setter: 1 }),
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::Builtin,
    },
    HookDefinition {
        name: "useReducer",
        semantics: HookSemantics::State,
        state_position: Some(StatePosition { value: 0, setter: 1 }),
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::Builtin,
    },
    HookDefinition {
        name: "useEffect",
        semantics: HookSemantics::Effect,
        state_position: None,
        effect_callback_position: Some(0),
        deps_position: Some(1),
        triggers_rerender: false,
        source: HookSource::Builtin,
    },
    HookDefinition {
        name: "useLayoutEffect",
        semantics: HookSemantics::Effect,
        state_position: None,
        effect_callback_position: Some(0),
        deps_position: Some(1),
        triggers_rerender: false,
        source: HookSource::Builtin,
    },
    HookDefinition {
        name: "useInsertionEffect",
        semantics: HookSemantics::Effect,
        state_position: None,
        effect_callback_position: Some(0),
        deps_position: Some(1),
        triggers_rerender: false,
        source: HookSource::Builtin,
    },
    HookDefinition {
        name: "useRef",
        semantics: HookSemantics::Ref,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: false,
        source: HookSource::Builtin,
    },
    HookDefinition {
        name: "useMemo",
        semantics: HookSemantics::Memo,
        state_position: None,
        effect_callback_position: Some(0),
        deps_position: Some(1),
        triggers_rerender: false,
        source: HookSource::Builtin,
    },
    HookDefinition {
        name: "useCallback",
        semantics: HookSemantics::Memo,
        state_position: None,
        effect_callback_position: Some(0),
        deps_position: Some(1),
        triggers_rerender: false,
        source: HookSource::Builtin,
    },
    HookDefinition {
        name: "useContext",
        semantics: HookSemantics::Context,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::Builtin,
    },
    HookDefinition {
        name: "useTransition",
        semantics: HookSemantics::State,
        state_position: Some(StatePosition { value: 0, setter: 1 }),
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: false,
        source: HookSource::Builtin,
    },
    HookDefinition {
        name: "useDeferredValue",
        semantics: HookSemantics::Memo,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: false,
        source: HookSource::Builtin,
    },
    HookDefinition {
        name: "useSyncExternalStore",
        semantics: HookSemantics::State,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::Builtin,
    },
    HookDefinition {
        name: "useId",
        semantics: HookSemantics::Unknown,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: false,
        source: HookSource::Builtin,
    },
    HookDefinition {
        name: "useImperativeHandle",
        semantics: HookSemantics::Ref,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: false,
        source: HookSource::Builtin,
    },
    HookDefinition {
        name: "useDebugValue",
        semantics: HookSemantics::Unknown,
        state_position: None,
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: false,
        source: HookSource::Builtin,
    },
    HookDefinition {
        name: "useOptimistic",
        semantics: HookSemantics::State,
        state_position: Some(StatePosition { value: 0, setter: 1 }),
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::Builtin,
    },
    HookDefinition {
        name: "useActionState",
        semantics: HookSemantics::State,
        state_position: Some(StatePosition { value: 0, setter: 1 }),
        effect_callback_position: None,
        deps_position: None,
        triggers_rerender: true,
        source: HookSource::Builtin,
    },
];
