pub mod cfg;
pub mod component;
pub mod expr;
pub mod free_vars;
pub mod function_ir;
pub mod hook_ir;
pub mod hooks;
pub mod remap;
pub mod source_range;
pub mod stmt;
pub mod types;

pub use cfg::{BasicBlock, CFG, Edge, EdgeKind, Terminator};
pub use component::ComponentIR;
pub use expr::{BinOp, Expr, Prim, UnaryOp};
pub use function_ir::FunctionIR;
pub use hook_ir::HookIR;
pub use hooks::HookEntry;
pub use remap::{remap_cfg, remap_expr, remap_hooks};
pub use source_range::{SourceRange, compute_line_starts, offset_to_range};
pub use stmt::Stmt;
pub use types::{BlockId, HookLabel, Symbol, Var};
